inicio registro
majg1987/liberte-app pull request #4
Opened 2022-07-12 15:37 UTC by majg1987

Vista de registro

2022-07-12 15:45 UTC, javier-bustillo requested changes
corremente

2022-07-12 15:53 UTC, javier-bustillo approved these changes

2022-07-13 09:14 UTC, divRobles approved these changes
ok

2022-07-13 09:15 UTC, divRobles approved these changes
ok

2022-07-13 09:15 UTC, RMjessica approved these changes

2022-07-13 09:16 UTC, merged

2022-07-13 09:16 UTC, divRobles commented
todo ok. Parece